### ISSUE TITLE
EPIC: support multi-dimensional testing

### ISSUE THREAD

**Issue by laurentsenta** [libp2p/test-plans#53]
> As a libp2p maintainer, I want the ability to define test suites that combine many implementations, many muxers, many transports, etc. Defining and running these test suites should be simple, and the outcome should be clear. It should be easy to trigger these test suites before a release. It should be easy to display these results in a readable form on a website.

eta: 2022Q4

## Tasks

- [x] https://github.com/libp2p/test-plans/issues/55
  - this will add the tooling used to describe, build, and run multiple combinations of tests in Testground
- [ ] Implement new parameters (muxers, transports, etc)
  - we need to define what the matrix looks like
  - we need to update the ping test to support these parameters
     - :warning: we need to make sure we test the connection from A to B AND from B to A (we don't at the moment)
- [ ] add the "expected RTT" test
  - This requires the ability to "generate" the expected outcomes for every cell in this N-D matrix,
- [ ] https://github.com/libp2p/test-plans/issues/61
- [ ] Generate a "nice" dashboard https://github.com/libp2p/test-plans/issues/62
  - @BigLep shared some notes in https://github.com/libp2p/test-plans/issues/55#issuecomment-1279304776
  - [ ] use case 1: As a maintainer, I want to check the status of our interop testing before making a release.
  - [ ] use case 2: As a user, I want to know more about libp2p interoperability capabilities.

### Follow-up tasks

- [ ] "optimize" by skipping versions libraries that are not used anymore (see notes below),
- [ ] "optimize" using artifact caching,

### A high-level approach:

1. first, we use versions resources file to generate "complex" test matrixes,
2. then we use another resource (data or code) to produce the expected RTT matrix,
3. then we generate the relevant composition file (as shown below), with the expected RTT as a parameter,
4. then we iterate through these test cases and call `testground run`.

### Configurations

Ideally, the libp2p team provides a resource file that contains the versions and their features:

```toml
[[groups]]
# go v0.42
GoVersion = '1.18'
Modfile = "go.v0.22.mod"
Selector = 'v0.42'
Implementation = 'go'
SupportedTransports = ["tcp", "quic", "webrtc"]
Muxer = ["yamux"]

[[groups]]
# go v0.22
GoVersion = '1.18'
Modfile = "go.v0.22.mod"
Selector = 'v0.22'
Implementation = 'go'
SupportedTransports = ["tcp", "quic"]
Muxer = ["mplex"]


[[groups]]
# rust v0.51
Libp2pVersion = 'v0.51.0'
Implementation = 'rust'
SupportedTransports = ["tcp", "webrtc"]

[[groups]]
# rust v0.47.0
Libp2pVersion = 'v0.47.0'
Implementation = 'rust'
SupportedTransports = ["tcp"]
Muxer = ["yamux", "mplex"]
```

And we'll create some way to have "meta-compositions" that can describe multiple tests and run many pairs together,

something like
(pseucode)
```
{ for every group }
    { if !group.SupportedTransports contains ENV.TESTED_TRANSPORT }
        { continue }
    { end }

    { if !group.SupportedTransports contains ENV.TESTED_MUXER }
        { continue }
    { end }

    [testground_instance]
    {}
{ endfor }
```

Called with

```bash
ENV.TESTED_TRANSPORT = "tcp"
ENV.TESTED_MUXER = "yamux"
testground run composition file
```

## Related discussions and issues

- https://github.com/libp2p/test-plans/pull/49#issuecomment-1267175415
- https://github.com/libp2p/test-plans/pull/44#discussion_r990832604
- https://github.com/libp2p/test-plans/issues/55

**Comment by laurentsenta** [comment]
note from sync w/ @marten-seemann (he was away for the chat yesterday and had related requests).

@mxinden @marten-seemann I have no strong feelings about this, but we might lose information between impromptu meetings. Do you feel the need to schedule some sort of "interop squad sync" where everyone joins at the same time?


Some more good ideas were brought up. A few notes:

### Generating Matrix Parameters

The point of this epic is to let the libp2p team define a multi-dimensional test matrix,
and make sure it's maintainable. This is covered by the configuration above.

Using this configuration file, we can generate multiple tests, for example:
- every pair that can communicate over quic.
- every group of versions that can use TCP + yamux.

Implicitly this configuration represents compatible pairs. This means we have a matrix of `implementation * versions * muxer * transports` and each cell in this matrix is YES (interoperable) or NO (not interoperable).

An extension to this matrix is the RTT use case: @marten-seemann needs to add "expected RTT" for each of these pairs. Each cell in the matrix will contain an expected RTT in milliseconds.

A high-level approach:

- first, we use the versions resources file (above) to generate the test matrix,
- then we use another resource (data or code) to produce the expected RTT matrix,
- then we generate the relevant composition file (as shown above), with the expected RTT as a parameter,
- then we iterate through these test cases and call `testground run`.

I plan to iterate through solutions:

- first, implement an interop suite that runs in CI and test pairs of instances, and generate "some" dashboards.
- second, extend this feature to support the full matrix of muxer * transports * etc...
- third, extends this feature to support the RTT matrix.

Unknown: this is focused on generating test pairs, how to express "I want to create a group with every webrtc-compatible implementation"? Do we need it?




### Supported version

The size of the test matrix will explode quickly. This should not be a problem to create the configuration files, but this will be a problem for the time to build & run test suites.

I believe EKS will solve some of this problem (with caching out of the box and having enough resources to enable parallelization), but we'll have to pick and choose which versions and combinations to test eventually.

One option is to test the most used version, see the diagram:

http://162.55.187.75:3000/d/CSQsORs7k/nebula?orgId=1&viewPanel=11
We have ~10 versions that cover ~60% of the network + "others"

We can use these metrics to enable/disable versions, probably something like:
- X latest versions,
- X most used versions

This solution sounds reasonable enough to keep this problem for later.

### Config Structure

keep in mind: muxer + security applies only to TCP, so it might be helpful to use a nested structure instead of:

```
conf:
  SupportedTransports = ["tcp", "quic", "webrtc"]
  Muxer = ["yamux"]
```

Something like this might represent our matrix better, and it might be easier to expand.

```
conf:
   transports:
       TCP:
          muxer: yamux
       quic: true
```

We don't have to decide on this now (data is easy to transform), I recommend we stick to the flat structure for now.

**Comment by marten-seemann** [comment]
> An extension to this matrix is the RTT use case: @marten-seemann needs to add "expected RTT" for each of these pairs. Each cell in the matrix will contain an expected RTT in milliseconds.

Minor correction: It’s expected handshake duration, and it’s a dimensionless number: the number of RTTs. Calculating the actual duration will be done by the test plan, based on that number and the RTT that’s used for the run.

**Comment by mxinden** [comment]
> ### Config Structure
> 
> keep in mind: muxer + security applies only to TCP, so it might be helpful to use a nested structure instead of:
> 
> ```
> conf:
>   SupportedTransports = ["tcp", "quic", "webrtc"]
>   Muxer = ["yamux"]
> ```
> 
> Something like this might represent our matrix better, and it might be easier to expand.
> 
> ```
> conf:
>    transports:
>        TCP:
>           muxer: yamux
>        quic: true
> ```
> 
> We don't have to decide on this now (data is easy to transform), I recommend we stick to the flat structure for now.

Given that we only have two muxers and two security protocols we can inline this into a single dimension in the first iteration. Example:

``` toml
[[groups]]
# go v0.22
GoVersion = '1.18'
Modfile = "go.v0.22.mod"
Selector = 'v0.22'
Implementation = 'go'
SupportedTransports = ["tcp/noise/mplex", "tcp/noise/yamux", "tcp/tls/mplex", "tcp/tls/yamux", "quic"]

[[groups]]
# rust v0.51
Libp2pVersion = 'v0.51.0'
Implementation = 'rust'
SupportedTransports = ["tcp/noise/mplex", "tcp/noise/yamux"]
```
